/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as TeachRouteImport } from './routes/teach'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CourseSlugRouteImport } from './routes/course.$slug'
import { Route as TeachIndexRouteImport } from './routes/teach.index'
import { Route as TeachSlugRouteImport } from './routes/teach.$slug'
import { Route as TeachNewRouteImport } from './routes/teach.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WatchCourseSlugLessonSlugRouteImport } from './routes/watch.$courseSlug.$lessonSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachRoute = TeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachIndexRoute = TeachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeachRoute,
} as any)
const TeachSlugRoute = TeachSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeachRoute,
} as any)
const TeachNewRoute = TeachNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TeachRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchCourseSlugLessonSlugRoute =
  WatchCourseSlugLessonSlugRouteImport.update({
    id: '/watch/$courseSlug/$lessonSlug',
    path: '/watch/$courseSlug/$lessonSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/teach': typeof TeachRouteWithChildren
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/users': typeof AdminUsersRoute
  '/course/$slug': typeof CourseSlugRoute
  '/teach/$slug': typeof TeachSlugRoute
  '/teach/new': typeof TeachNewRoute
  '/admin/': typeof AdminIndexRoute
  '/teach/': typeof TeachIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/watch/$courseSlug/$lessonSlug': typeof WatchCourseSlugLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/users': typeof AdminUsersRoute
  '/course/$slug': typeof CourseSlugRoute
  '/teach/$slug': typeof TeachSlugRoute
  '/teach/new': typeof TeachNewRoute
  '/admin': typeof AdminIndexRoute
  '/teach': typeof TeachIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/watch/$courseSlug/$lessonSlug': typeof WatchCourseSlugLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/teach': typeof TeachRouteWithChildren
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/users': typeof AdminUsersRoute
  '/course/$slug': typeof CourseSlugRoute
  '/teach/$slug': typeof TeachSlugRoute
  '/teach/new': typeof TeachNewRoute
  '/admin/': typeof AdminIndexRoute
  '/teach/': typeof TeachIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/watch/$courseSlug/$lessonSlug': typeof WatchCourseSlugLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalog'
    | '/dashboard'
    | '/library'
    | '/login'
    | '/progress'
    | '/teach'
    | '/admin/courses'
    | '/admin/users'
    | '/course/$slug'
    | '/teach/$slug'
    | '/teach/new'
    | '/admin/'
    | '/teach/'
    | '/api/auth/$'
    | '/watch/$courseSlug/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/dashboard'
    | '/library'
    | '/login'
    | '/progress'
    | '/admin/courses'
    | '/admin/users'
    | '/course/$slug'
    | '/teach/$slug'
    | '/teach/new'
    | '/admin'
    | '/teach'
    | '/api/auth/$'
    | '/watch/$courseSlug/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalog'
    | '/dashboard'
    | '/library'
    | '/login'
    | '/progress'
    | '/teach'
    | '/admin/courses'
    | '/admin/users'
    | '/course/$slug'
    | '/teach/$slug'
    | '/teach/new'
    | '/admin/'
    | '/teach/'
    | '/api/auth/$'
    | '/watch/$courseSlug/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  DashboardRoute: typeof DashboardRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  TeachRoute: typeof TeachRouteWithChildren
  CourseSlugRoute: typeof CourseSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  WatchCourseSlugLessonSlugRoute: typeof WatchCourseSlugLessonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach': {
      id: '/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof TeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/course/$slug': {
      id: '/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach/': {
      id: '/teach/'
      path: '/'
      fullPath: '/teach/'
      preLoaderRoute: typeof TeachIndexRouteImport
      parentRoute: typeof TeachRoute
    }
    '/teach/$slug': {
      id: '/teach/$slug'
      path: '/$slug'
      fullPath: '/teach/$slug'
      preLoaderRoute: typeof TeachSlugRouteImport
      parentRoute: typeof TeachRoute
    }
    '/teach/new': {
      id: '/teach/new'
      path: '/new'
      fullPath: '/teach/new'
      preLoaderRoute: typeof TeachNewRouteImport
      parentRoute: typeof TeachRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$courseSlug/$lessonSlug': {
      id: '/watch/$courseSlug/$lessonSlug'
      path: '/watch/$courseSlug/$lessonSlug'
      fullPath: '/watch/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof WatchCourseSlugLessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoursesRoute: AdminCoursesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TeachRouteChildren {
  TeachSlugRoute: typeof TeachSlugRoute
  TeachNewRoute: typeof TeachNewRoute
  TeachIndexRoute: typeof TeachIndexRoute
}

const TeachRouteChildren: TeachRouteChildren = {
  TeachSlugRoute: TeachSlugRoute,
  TeachNewRoute: TeachNewRoute,
  TeachIndexRoute: TeachIndexRoute,
}

const TeachRouteWithChildren = TeachRoute._addFileChildren(TeachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogRoute: CatalogRoute,
  DashboardRoute: DashboardRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  TeachRoute: TeachRouteWithChildren,
  CourseSlugRoute: CourseSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  WatchCourseSlugLessonSlugRoute: WatchCourseSlugLessonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
